CREATE TABLE PRODUCTS (
    ID int,
    NAME varchar(255) NOT NULL,
    CATEGORY varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_PRICE_HISTORY (
    PRODUCT_PRICE_ID int,
    PRICE int,
    START_DATE DATE,
    END_DATE DATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    PRIMARY KEY (PRODUCT_PRICE_ID)
);


select * from PRODUCTS p, PRODUCT_PRICE_HISTORY pp where p.ID = pp.PRODUCT_ID